version: '3'
services:
    minecraft:
        build: ./servers/minecraft/
        ports:
            - "25565:25565"
        volumes:
            - ./data/minecraft/world:/usr/minecraft/world
        container_name: "minecraft-java-server"
        image: docker.io/argentumknight/minecraft-server:1.0
    express:
        # build: ./servers/express/
        ports:
            - "8888:8888"
        volumes:
            - ./data/vault:/app/vault
        container_name: "expressito"
        image: docker.io/argentumknight/express:1.0