FROM ubuntu
WORKDIR /etc/samba
RUN apt-get update && \
apt-get install systemctl -y && \
apt-get install samba -y && \
systemctl start smbd
# COPY smb.conf .
EXPOSE 137/udp 138/udp 139 445
# CMD [ "systemctl","start","smbd"]
# ENTRYPOINT [ "tail -f /dev/null" ]
# ENTRYPOINT systemctl start smbd